CREATE TABLE IF NOT EXISTS persistent_logins (
  username VARCHAR(64) NOT NULL,
  series VARCHAR(64) PRIMARY KEY,
  token VARCHAR(64) NOT NULL,
  last_used TIMESTAMP NOT NULL
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS restricted BOOLEAN;
UPDATE users SET restricted = FALSE WHERE restricted IS NULL;
ALTER TABLE users ALTER COLUMN restricted SET DEFAULT FALSE;
ALTER TABLE users ALTER COLUMN restricted SET NOT NULL;
