CREATE TABLE IF NOT EXISTS persistent_logins (
  username VARCHAR(64) NOT NULL,
  series VARCHAR(64) PRIMARY KEY,
  token VARCHAR(64) NOT NULL,
  last_used TIMESTAMP NOT NULL
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS restricted BOOLEAN;
UPDATE users SET restricted = FALSE WHERE restricted IS NULL;
ALTER TABLE users ALTER COLUMN restricted SET DEFAULT FALSE;
ALTER TABLE users ALTER COLUMN restricted SET NOT NULL;

ALTER TABLE meal_plans ADD COLUMN IF NOT EXISTS active BOOLEAN;
UPDATE meal_plans SET active = TRUE WHERE active IS NULL;
ALTER TABLE meal_plans ALTER COLUMN active SET DEFAULT TRUE;
ALTER TABLE meal_plans ALTER COLUMN active SET NOT NULL;
ALTER TABLE meal_plans ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP;

ALTER TABLE grocery_items ADD COLUMN IF NOT EXISTS source_plan_id BIGINT;
ALTER TABLE grocery_items ADD COLUMN IF NOT EXISTS source_plan_title VARCHAR(220);
ALTER TABLE grocery_items ADD COLUMN IF NOT EXISTS source_plan_day VARCHAR(60);
